#:schema https://raw.githubusercontent.com/ghishadow/lapce-schema/main/theme.schema.json

[color-theme]
name = "Cute Light Pink"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]
white = "#FAFAFA"
black = "#383A42"
grey = "#E5E5E6"
light_grey = "#D3D3D3"
blue = "#83A1FF"
red = "#E45649"
yellow = "#FF9E3B"
green = "#50A14F"
purple = "#793DC3"
cyan = "#5DC0C7"
magenta = "#C13291"
orange = "#F25B43"

[color-theme.syntax]
"comment" = "#A0A1A7"

"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"

"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"

"keyword" = "$purple"
"selfKeyword" = "$purple"

"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"

"string" = "$green"
"string.escape" = "$cyan"

"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"

"punctuation.delimiter" = "$black"
"text.title" = "$orange"
"text.uri" = "$cyan"
"text.reference" = "$yellow"
"variable" = "$red"
"variable.other.member" = "$green"
"tag" = "$blue"

[color-theme.ui]
"lapce.active_tab" = "#FEEEEC"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#B4B4B4"
"lapce.border" = "#B4B4B4"
"lapce.scroll_bar" = "#B4B4B4"

"terminal.cursor" = "$black"
"terminal.foreground" = "$black"
"terminal.background" = "#FEEEECFF"
"terminal.white" = "$black"
"terminal.black" = "$white"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "#FFFFFF"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "$black"

"editor.background" = "#FEEEEC"
"editor.foreground" = "$black"
"editor.dim" = "#A0A1A7"
"editor.focus" = "#000000"
"editor.caret" = "#526FFF"
"editor.selection" = "#f1b2d2"
"editor.current_line" = "#b9cdf0"
"editor.link" = "$cyan"

"inlay_hint.foreground" = "#000000"
"inlay_hint.background" = "#528bFF55"

"source_control.added" = "#50A14F32"
"source_control.removed" = "#FF526632"
"source_control.modified" = "#0184BC32"

"palette.background" = "#fceaf1"
"palette.current" = "#ffb5bb"

"completion.background" = "#fceaf1"
"completion.current" = "#ffb5bb"

"hover.background" = "#EAEAEB"

"activity.background" = "#2e2638"
"activity.current" = "#ffb5bb"

"panel.background" = "#fceaf1ff"
"panel.current" = "#ffb5bb"
"panel.hovered" = "#E4E4E6"

"status.background" = "#FD7094"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$purple"

"markdown.blockquote" = "#686868"

"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = "$white"

# tab
"lapce.tab.active.background" = "$white"
"lapce.tab.active.foreground" = "$black"
"lapce.tab.active.underline" = "#528BFF"

"lapce.tab.inactive.background" = "#EAEAEB"
"lapce.tab.inactive.foreground" = "$black"
"lapce.tab.inactive.underline" = "#528BFF77"

"lapce.tab.separator" = "#B4B4B4"

"lapce.icon.active" = "$black"
"lapce.icon.inactive" = "#A0A1A7"

"lapce.remote.local" = "#4078F2"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"

"lapce.plugin.name" = "#444444"
"lapce.plugin.description" = "$black"
"lapce.plugin.author" = "#707070"


"editor.visible_whitespace" = "$grey"
"editor.indent_guide" = "$grey"
"editor.drag_drop_background" = "#79c1fc33"
"editor.drag_drop_tab_background" = "#0b0e1433"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#E4564920"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "#C1840120"
"error_lens.other.foreground" = "#A0A1A7"
"error_lens.other.background" = "#A0A1A720"

"palette.foreground" = "$black"
"palette.current.background" = "#DBDBDC"
"palette.current.foreground" = "$black"

"panel.foreground" = "$black"
"panel.foreground.dim" = "#A0A1A7"
"panel.current.background" = "#DBDBDC"
"panel.current.foreground" = "$black"
"panel.current.foreground.dim" = "#A0A1A7"
"panel.hovered.background" = "#E4E4E6"
"panel.hovered.foreground" = "$black"
"panel.hovered.foreground.dim" = "#A0A1A7"
