name = "lightpink"
version = "0.2.2"
display-name = "Cute Light Pink"
description = "Cute Light Pink"
author = "ghishadow"
repository = "ghishadow/light-pink-theme"
color-themes = ["light-pink.toml"]
