#:schema https://raw.githubusercontent.com/ghishadow/lapce-schema/main/volt.theme.schema.json

name = "lightpink"
version = "0.2.3"
display-name = "Light Pink"
description = "Cute Light Pink"
author = "ghishadow"
repository = "ghishadow/light-pink-theme"
color-themes = ["light-pink.toml"]
